### ISSUE TITLE
syntax error, unexpected ':', expecting =>

### ISSUE THREAD

**Issue by richddr** [Netflix/batch_request_client#4]
Rails `4.2.7.1`, Ruby `2.1.5`

When trying to run a rails app with this gem installed I get the following error:
```
/home/foo/.rvm/gems/ruby-2.1.5@foo_app/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require': /home/foo/.rvm/gems/ruby-2.1.5@foo_app/gems/batch_request_client-0.1.4/lib/batch_request_client/batch_util.rb:22: syntax error, unexpected ':', expecting => (SyntaxError)
        "method": method,
                 ^
/home/foo/.rvm/gems/ruby-2.1.5@foo_app/gems/batch_request_client-0.1.4/lib/batch_request_client/batch_util.rb:23: syntax error, unexpected ':', expecting :: or '[' or '.'
        "url": "#{url}",
              ^
/home/foo/.rvm/gems/ruby-2.1.5@foo_app/gems/batch_request_client-0.1.4/lib/batch_request_client/batch_util.rb:23: syntax error, unexpected ',', expecting keyword_end
/home/foo/.rvm/gems/ruby-2.1.5@foo_app/gems/batch_request_client-0.1.4/lib/batch_request_client/batch_util.rb:24: syntax error, unexpected ':', expecting keyword_end
        "body": item
               ^
/home/foo/.rvm/gems/ruby-2.1.5@foo_app/gems/batch_request_client-0.1.4/lib/batch_request_client/batch_util.rb:30: syntax error, unexpected ':', expecting =>
        "requests": requests
                   ^
/home/foo/.rvm/gems/ruby-2.1.5@foo_app/gems/batch_request_client-0.1.4/lib/batch_request_client/batch_util.rb:38: syntax error, unexpected end-of-input, expecting keyword_end
  from /home/foo/.rvm/gems/ruby-2.1.5@foo_app/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
  from /home/foo/.rvm/gems/ruby-2.1.5@foo_app/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
  from /home/foo/.rvm/gems/ruby-2.1.5@foo_app/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
  from /home/foo/.rvm/gems/ruby-2.1.5@foo_app/gems/batch_request_client-0.1.4/lib/batch_request_client.rb:2:in `<top (required)>'
  from /home/foo/.rvm/gems/ruby-2.1.5@foo_app/gems/bundler-1.15.4/lib/bundler/runtime.rb:82:in `require'
  from /home/foo/.rvm/gems/ruby-2.1.5@foo_app/gems/bundler-1.15.4/lib/bundler/runtime.rb:82:in `block (2 levels) in require'
  from /home/foo/.rvm/gems/ruby-2.1.5@foo_app/gems/bundler-1.15.4/lib/bundler/runtime.rb:77:in `each'
  from /home/foo/.rvm/gems/ruby-2.1.5@foo_app/gems/bundler-1.15.4/lib/bundler/runtime.rb:77:in `block in require'
  from /home/foo/.rvm/gems/ruby-2.1.5@foo_app/gems/bundler-1.15.4/lib/bundler/runtime.rb:66:in `each'
  from /home/foo/.rvm/gems/ruby-2.1.5@foo_app/gems/bundler-1.15.4/lib/bundler/runtime.rb:66:in `require'
  from /home/foo/.rvm/gems/ruby-2.1.5@foo_app/gems/bundler-1.15.4/lib/bundler.rb:108:in `require'
  from /home/foo/foo_dir/foo_app/config/application.rb:7:in `<top (required)>'
  from /home/foo/.rvm/gems/ruby-2.1.5@foo_app/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:78:in `require'
  from /home/foo/.rvm/gems/ruby-2.1.5@foo_app/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:78:in `block in server'
  from /home/foo/.rvm/gems/ruby-2.1.5@foo_app/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
  from /home/foo/.rvm/gems/ruby-2.1.5@foo_app/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:75:in `server'
  from /home/foo/.rvm/gems/ruby-2.1.5@foo_app/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  from /home/foo/.rvm/gems/ruby-2.1.5@foo_app/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
  from /home/foo/foo_dir/foo_app/bin/rails:4:in `require'
  from /home/foo/foo_dir/foo_app/bin/rails:4:in `<top (required)>'
  from /home/foo/.rvm/gems/ruby-2.1.5@foo_app/gems/spring-1.6.4/lib/spring/client/rails.rb:28:in `load'
  from /home/foo/.rvm/gems/ruby-2.1.5@foo_app/gems/spring-1.6.4/lib/spring/client/rails.rb:28:in `call'
  from /home/foo/.rvm/gems/ruby-2.1.5@foo_app/gems/spring-1.6.4/lib/spring/client/command.rb:7:in `call'
  from /home/foo/.rvm/gems/ruby-2.1.5@foo_app/gems/spring-1.6.4/lib/spring/client.rb:28:in `run'
  from /home/foo/.rvm/gems/ruby-2.1.5@foo_app/gems/spring-1.6.4/bin/spring:49:in `<top (required)>'
  from /home/foo/.rvm/gems/ruby-2.1.5@foo_app/bin/spring:23:in `load'
  from /home/foo/.rvm/gems/ruby-2.1.5@foo_app/bin/spring:23:in `<main>'
  from /home/foo/.rvm/gems/ruby-2.1.5@foo_app/bin/ruby_executable_hooks:15:in `eval'
  from /home/foo/.rvm/gems/ruby-2.1.5@foo_app/bin/ruby_executable_hooks:15:in `<main>'
```
Due to: 

```ruby
    def request_signature(item, method, url)
      {
        "method": method,
        "url": "#{url}",
        "body": item
      }
    end

    def padded_response(requests)
      {
        "requests": requests
      }
    end
```

Which should be:

```ruby
    def request_signature(item, method, url)
      {
        'method' => method,
        'url' => url,
        'body' => item
      }
    end

    def padded_response(requests)
      {
        'requests' => requests
      }
    end
```

Changing that allows the app to run successfully. I can submit a PR for this.

**Comment by richddr** [comment]
@sriniwasgr
